name = "tiny-push"
main = "worker.mjs"
compatibility_date = "2025-09-10"

[vars]
APP_URL = "https://timekeeper.patrickreinbold.com"

[[kv_namespaces]]
binding = "SUBS"
id = "49302ae415c745f38771fba3f9d3697f"

[triggers]
crons = ["0 * * * *"]   # every hour on the hour
